### ISSUE TITLE
OS error 24

### ISSUE THREAD

**Issue by JDface** [XiaohangZhan/face_recognition_framework#5]
Hello:

When i run this step 4 "sh experiments/webface/res50-bs64-sz224-ep35/train.sh". i am getting error message.
OSERROR: [Errno 24] Too many files open.

It is all from reduction.py line 191 and resource_sharer.py line 48

Any help to resolve this is greatly appreciated.

**Comment by JDface** [comment]
not sure but you may not be aware that your code is not working or its not tested thoroughly. As you can see that i am only one raising the issue???

**Comment by XiaohangZhan** [comment]
It depends on the configuration of your server. Reducing `workers` in the `config.yaml` might solve it. If not, please Google it, there are plenty of discussions on this issue, since it's not related to my code.

**Comment by Light--** [comment]
even i reduce the num-workers to 2, still report too many open files error

```
$ sh experiments/webface/res50-bs64-sz224-ep35/train.sh
Creating model on [4] gpus: 0,1,2,3
Origin Size: 493456     Aligned Size: 493568
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 149, in _serve
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
Process Process-2:
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 319, in reduce_storage
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/reduction.py", line 194, in DupFd
    send(conn, destination_pid)  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 48, in __init__

OSError: [Errno 24] Too many open files
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 50, in send
    reduction.send_handle(conn, new_fd, pid)
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/reduction.py", line 179, in send_handle
    with socket.fromfd(conn.fileno(), socket.AF_UNIX, socket.SOCK_STREAM) as s:
  File "/home/user1/miniconda3/lib/python3.7/socket.py", line 463, in fromfd
    nfd = dup(fd)
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 85, in _worker_loop
    r = index_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 276, in rebuild_storage_fd
    fd = df.detach()
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/reduction.py", line 155, in recvfds
    raise EOFError
EOFError
Traceback (most recent call last):
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/user1/miniconda3/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/home/user1/miniconda3/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 28959) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 458, in <module>
    main()
  File "main.py", line 242, in main
    train(train_loader, model, optimizer, epoch, args.train.loss_weight, tb_logger, count)
  File "main.py", line 276, in train
    for i, all_in in enumerate(zip(*tuple(train_loader))):
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 576, in __next__
    idx, batch = self._get_batch()
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 553, in _get_batch
    success, data = self._try_get_batch()
  File "/home/user1/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 519, in _try_get_batch
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 28959) exited unexpectedly
```

so i reduce to 1, it report another error:
```
$ sh experiments/webface/res50-bs64-sz224-ep35/train.sh
Creating model on [4] gpus: 0,1,2,3
Origin Size: 493456     Aligned Size: 493568
/home/user1/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "main.py", line 458, in <module>
    main()
  File "main.py", line 242, in main
    train(train_loader, model, optimizer, epoch, args.train.loss_weight, tb_logger, count)
  File "main.py", line 304, in train
    losses[k].update(loss[k].mean().data[0])
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
```
Finally i solved by ：
1， keep num_workers 16 in config.yaml 
2, add ```torch.multiprocessing.set_sharing_strategy('file_system') ``` in main.py
3, modified main.py ``` # 304 losses[k].update(loss[k].mean().data[0]) ``` to ``` # 304 losses[k].update(loss[k].mean().item()) ``` and  ``` # 370 losses[k].update(loss[k].data[0]) ``` to ``` # 370 losses[k].update(loss[k].item()) ```

**Comment by XiaohangZhan** [comment]
I'm not sure the reason for the `Too many open files` issue. I did not encounter it before. But the `item()` issue is due to the PyTorch version.  My experiments were with PyTorch=0.3.1. I recommend using python=3.6 and pytorch=0.3.1 to see if the previous issue could be resolved.

**Comment by XiaohangZhan** [comment]
Besides, this is a solution for your reference: https://github.com/pytorch/pytorch/issues/11201

**Comment by Light--** [comment]
> Besides, this is a solution for your reference: [pytorch/pytorch#11201]

Thx very much, i have solved that and updated the comments above. Will you consider modify the code to make it compatiable with more situations in the future? I can submit a pull request based on my modifications if you agree. Thank you.

my pytorch version: 1.1.0

**Comment by XiaohangZhan** [comment]
I'm too busy recently. Maybe I will take care of this repo in the future. Thank you so much. You can submit the pull request.
